CREATE TABLE `Metals`
(
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `metal` TEXT NOT NULL,
    `price` NUMERIC(5,2) NOT NULL
);

CREATE TABLE `Sizes`
(
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `carets` NUMERIC(5,2) NOT NULL,
    `price` NUMERIC(5,2) NOT NULL
);

CREATE TABLE `Styles`
(
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `style` NVARCHAR(160) NOT NULL,
    `price` NUMERIC(5,2) NOT NULL
);

CREATE TABLE `Types`
(
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `type` NVARCHAR(160) NOT NULL
);

CREATE TABLE `Orders`
(
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `metal_id` INTEGER NOT NULL,
    `size_id` INTEGER NOT NULL,
    `style_id` INTEGER NOT NULL,
    `type_id` INTEGER NOT NULL,
    FOREIGN KEY(`metal_id`) REFERENCES `Metals`(`id`),
    FOREIGN KEY(`size_id`) REFERENCES `Sizes`(`id`),
    FOREIGN KEY(`style_id`) REFERENCES `Styles`(`id`),
    FOREIGN KEY(`type_id`) REFERENCES `Types`(`id`)
);

INSERT INTO 'Metals' VALUES (NULL, 'Sterling Silver',12.42);
INSERT INTO 'Metals' VALUES (NULL, '14K Gold',736.4);
INSERT INTO 'Metals' VALUES (NULL, '24K Gold',1258.9);
INSERT INTO 'Metals' VALUES (NULL, 'Platinum',795.45);
INSERT INTO 'Metals' VALUES (NULL, 'Palladium',1241);

INSERT INTO 'Types' VALUES (NULL, 'Ring');
INSERT INTO 'Types' VALUES (NULL, 'Earing');
INSERT INTO 'Types' VALUES (NULL, 'Necklace');

INSERT INTO 'Sizes' VALUES (NULL, 0.5, 405);
INSERT INTO 'Sizes' VALUES (NULL, 0.75, 782);
INSERT INTO 'Sizes' VALUES (NULL, 1, 1470);
INSERT INTO 'Sizes' VALUES (NULL, 1.5, 1997);
INSERT INTO 'Sizes' VALUES (NULL, 2, 3638);

INSERT INTO 'Styles' VALUES (NULL, 'Classic', 500);
INSERT INTO 'Styles' VALUES (NULL, 'Modern', 710);
INSERT INTO 'Styles' VALUES (NULL, 'Vintage', 965);

INSERT INTO 'Orders' VALUES (NULL, 3,1,1,2);
INSERT INTO 'Orders' VALUES (NULL, 1,1,1,1);
INSERT INTO 'Orders' VALUES (NULL, 2,1,3,1);
INSERT INTO 'Orders' VALUES (NULL, 5,4,3,3);